layout_spectrum: 0.07313389
typography_spectrum: 0.2840085
color:
  saturation: 0.8582095
  lightness: 0.12054
  brandStrength: 0.9093118
  rhythmicContrast: 0.0172554
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
name: Beyond Cleaning  LLC
